// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526154434_moreQuoutesAndFavoriteMotivatorMaybe")]
    partial class moreQuoutesAndFavoriteMotivatorMaybe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("api.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "V",
                            Text = "Gør det i dag - det som du ellers kan overveje at udsætte til i morgen!"
                        },
                        new
                        {
                            Id = 2,
                            Author = "A",
                            Text = "Små steps/sejre hver dag (mod et større mål) kan føre til store resultater."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Steve Jobs",
                            Text = "The only way to do great work is to love what you do."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Albert Einstein",
                            Text = "Strive not to be a success, but rather to be of value."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Steve Jobs",
                            Text = "Your time is limited, so don’t waste it living someone else’s life."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Buddha",
                            Text = "The mind is everything. What you think you become."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Peter Drucker",
                            Text = "The best way to predict the future is to create it."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Winston Churchill",
                            Text = "Success is not final, failure is not fatal: It is the courage to continue that counts."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Theodore Roosevelt",
                            Text = "Believe you can and you're halfway there."
                        },
                        new
                        {
                            Id = 10,
                            Author = "William James",
                            Text = "Act as if what you do makes a difference. It does."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Confucius",
                            Text = "It does not matter how slowly you go as long as you do not stop."
                        },
                        new
                        {
                            Id = 12,
                            Author = "Eleanor Roosevelt",
                            Text = "The future belongs to those who believe in the beauty of their dreams."
                        },
                        new
                        {
                            Id = 13,
                            Author = "William Butler Yeats",
                            Text = "Do not wait to strike till the iron is hot; but make it hot by striking."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Walt Whitman",
                            Text = "Keep your face always toward the sunshine, and shadows will fall behind you."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Ralph Waldo Emerson",
                            Text = "What lies behind us and what lies before us are tiny matters compared to what lies within us."
                        });
                });

            modelBuilder.Entity("api.Models.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoTasks");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("favoriteMotivator")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2025, 4, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test@ellernoget.com",
                            PasswordHash = "$2a$11$IsepszmC6snjPcfCcAmo5uctrPqXcLzRRoEVkpywIOw2kG7T./fOu",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("api.Models.ToDoTask", b =>
                {
                    b.HasOne("api.Models.User", "User")
                        .WithMany("ToDoTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("ToDoTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
